### PR TITLE
update to latest zig

### PR DESCRIPTION
**Pull request by joachimschmidt557**
Update the code for the latest zig from master branch. The benchmarking code using `zig-bench` has been commented out because `zig-bench` itself needs to be updated to the latest zig.

### CODE REVIEW

**Comment by Hejsil** [comment]
I'll be using Zig 0.5.0 until the AUR gets 0.6.0. It'll probably be a few weeks before that happens. I'll then update `zig-bench` and then we can merge this. Sounds good?

**Comment by joachimschmidt557** [comment]
Ok, sounds good. In case there are any more breaking changes before 0.6.0, I'll include them in this PR as well.

**Comment by joachimschmidt557** [comment]
I've updated the code for `0.6.0` and reactivated the benchmark just now.

**Comment by Hejsil** [comment]
Cool, thanks!

**Pull request merged**
